# Generated by Django 4.2 on 2024-07-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('A', 'Agua'), ('E', 'Electrico'), ('F', 'Fuego'), ('L', 'Lagartija'), ('P', 'Planta'), ('T', 'Tierra')], max_length=30)),
                ('weight', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('height', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
            ],
        ),
    ]
